### Site Settings ###
title               : Jovian Dsouza
description         : >-
                      "I turn coffee :coffee: into code,
                      use tabs over spaces
                      and never broke production."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : https://github.com/Jovian-Dsouza/Jovian-Dsouza.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : https://github.com/Jovian-Dsouza/Jovian-Dsouza.github.io


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Jovian Dsouza
  image             : https://bit.ly/2KCvgVJ
# behance           : Jovian-Dsouza
# dribbble          : your_username
  email             : dsouzajovian123@gmail.com
  facebook          : jovian.dsouza.7
  github            : Jovian-Dsouza
  gitlab            : Jovian-Dsouza
  instagram         : jovian.dsouza.19
  linkedin          : joviandsouza
  medium            : JovianDsouza
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : DsouzaJovian
# vimeo             : your_username
  youtube           : Jovi_tech


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - docker-compose.yaml
